spring:
  application:
    name: eureka-client-one
server:
  port: 10001
eureka:
  client:
    healthcheck:
      # 开启默认健康检查
      enabled: true
    service-url:
      defaultZone : http://localhost:8761/eureka/

